name: "build-tests"

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  build_eppp:
    name: Build
    strategy:
      matrix:
        idf_ver: ["release-v5.5", "release-v5.4", "release-v5.3"]
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - name: Checkout picoquic
        uses: actions/checkout@v3
      - name: Build with IDF-${{ matrix.idf_ver }}
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          ./scripts/get_deps.sh
          cd examples/pico-mqtt
          idf.py build
          if [ "${{ matrix.idf_ver }}" == "release-v5.5" ]; then
            rm -rf build sdkconfig
            idf.py --preview set-target linux
            idf.py build
            ./build/pico-mqtt.elf
          fi
          cd ../mqtt
          idf.py build
